apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devflix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zangetsu2/devflix.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
