apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devflix-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: devflix.local
    http:
      paths:
      - path: /frontend(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /voting
        pathType: Prefix
        backend:
          service:
            name: voting
            port:
              number: 8080
      - path: /recommendation
        pathType: Prefix
        backend:
          service:
            name: recommendation
            port:
              number: 8000